pipeline:
  projectIdentifier: templates
  orgIdentifier: Platform
  tags: {}
  properties:
    ci:
      codebase:
        repoName: migdal.platform.templates.lib.python
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: account.python_lib_ci
          versionLabel: 1.0.0
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Pipeline
        spec:
          org: Platform
          pipeline: CDlibtemplate
          project: templates
          inputs:
            identifier: CDlibtemplate
            properties:
              ci:
                codebase:
                  build:
                    spec:
                      branch: main
                    type: branch
  name: CI-lib-template
  identifier: CIlibtemplate
