pipeline:
  projectIdentifier: templates
  orgIdentifier: Platform
  tags: {}
  properties:
    ci:
      codebase:
        repoName: migdal.platform.templates.lib.python
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: account.python_lib_ci
          versionLabel: 1.0.1
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Pipeline
        spec:
          org: Platform
          pipeline: CDtemplate
          project: templates
          inputs:
            identifier: CDtemplate
            variables:
              - name: image_tag
                type: String
                value: <+pipeline.stages.build.spec.execution.steps.Push.steps.BuildAndPushECR.artifact_Push_BuildAndPushECR.stepArtifacts.publishedImageArtifacts[0].tag>
              - name: release
                type: String
                value: "false"
  name: CI-template
  identifier: CItemplate
