site_name: migdal.data.ods.glue-sdk 

nav:
  - Home: README.md 
  - CHANGELOG: CHANGELOG.md
  //Update to relevant project docs you have added
  // Example  
  - example: example.md
    
plugins:
  - techdocs-core